### ISSUE TITLE
写都写了不如直接搞成一可引用的lib吧

### ISSUE THREAD

**Issue by zs1973** [TheMelody/ComposeTextEffect#2]
写都写了不如直接搞成一可引用的lib吧  哈哈哈哈

**Comment by TheMelody** [comment]
> 写都写了不如直接搞成一可引用的lib吧 哈哈哈哈

哈哈哈，好的好的，是只要折叠和展开那个功能吗？

**Comment by zs1973** [comment]
> 

> > 写都写了不如直接搞成一可引用的lib吧 哈哈哈哈
> 哈哈哈，好的好的，是只要折叠和展开那个功能吗？
是的呀 可以慢慢往下迭代呗  hhhh
