### ISSUE TITLE
那种文本提前换行的需要怎么处理 

### ISSUE THREAD

**Issue by artillerymans** [TheMelody/ComposeTextEffect#4]

**Comment by TheMelody** [comment]
啥意思？你要做成什么样，现在是什么样，有什么问题，描述清楚再来

**Comment by artillerymans** [comment]
![image](https://github.com/TheMelody/ComposeTextEffect/assets/16060581/61f020e9-2122-49fa-8675-50ea74113eeb)
类似这种的 红色框代表一个Text控件最大的宽度，第一个红色框在末尾蓝色部分空了一部分，提前换到了第二行,我希望能做到第二个红色框内的内容一样左右完全贴边后再把文本换到第二行

**Comment by TheMelody** [comment]
> ![image](https://user-images.githubusercontent.com/16060581/269800510-61f020e9-2122-49fa-8675-50ea74113eeb.png) 类似这种的 红色框代表一个Text控件最大的宽度，第一个红色框在末尾蓝色部分空了一部分，提前换到了第二行,我希望能做到第二个红色框内的内容一样左右完全贴边后再把文本换到第二行

这个目前我这个库没有写这个例子，你可以自己尝试实现
